// Generated by CoffeeScript 1.10.0
(function() {
  describe('given a record set result in KatyQuery format', function() {
    describe('with no joins', function() {
      return it('should bind as expected', function() {});
    });
    describe('with a one to one inner join', function() {
      return it('should bind as expected', function() {});
    });
    describe('with a one to many inner join', function() {
      return it('should bind as expected', function() {});
    });
    return describe('with a many to many inner join', function() {
      return it('should bind as expected', function() {});
    });
  });

}).call(this);

//# sourceMappingURL=lib.js.map
